---

    ## standard mode: different unique keys per host
  - include_tasks: get_keys_wrapper.yml
    when: >-
      not _iter_users.value.ssh.batched


  - block:

        ## batched mode: same global keys for all hosts
      - include_tasks: get_keys_wrapper.yml

    run_once: true
    delegate_to: >-
      {{ _iter_users.value.secret_handler
       | default((ansible_play_batch | first), True) }}
    when: >-
      _iter_users.value.ssh.batched


  - include_tasks: auth_sshkeys.yml
    loop: "{{ _tmp_user_sshkeys_pub }}"
    loop_control:
      loop_var: _iter_sshkeys
      extended: true

      ## recommended for saving memory when not needed (which it is not in our case) but unfortunately rather new setting, which is not yet avaible on many systems
      ## TODO: reactivate when it seems save to do so
      ##extended_allitems: false

