---

  - set_fact:
      _tmp_java_cert_handled: true


  - name: ensure that java cert package is installed
    package: 
      name: 
        - java-cacerts
      state: present


  - include_tasks: java_certs_alpine_loop.yml
    loop: "{{ handle_system_certs_args_normed.eco_systems.java._jvms }}"
    loop_control:
      loop_var: _iter_jvm

