---

  - block:

        ##
        ## keyfile direct link dowload variant
        ##
      - block:

           ## TODO: wrap with proper py gpg ansible module
         - name: get / update source signing key
           ansible.builtin.get_url: "{{ _iter_apt_sources.signing.config }}"


           ## TODO: wrap with proper py gpg ansible module
         - name: de-armor base64 / ascii armored signing key
           ansible.builtin.shell: |
             kf='{{ _iter_apt_sources.signing.config.dest }}'
             mv "${kf}" "${kf}.ascii"

             cat "${kf}.ascii" | gpg --dearmor > "${kf}"

             rm "${kf}.ascii"

           changed_when: false
           when: _iter_apt_sources.signing.de_armor | default(False)

        when: >-
          (_iter_apt_sources.signing.config.url | default(False)) is truthy


        ##
        ## getting key(s) by fingerprints and keyserver variant
        ##
      - block:

          - name: create tmp gpg homedir
            ansible.builtin.tempfile:
              state: directory
            changed_when: false
            register: _tmpres_tmpdir


            ## TODO: wrap with proper py gpg ansible module
          - name: import gpg keys from key-servers
            ansible.builtin.shell: >-
              gpg --no-default-keyring --keyring
              '{{ _iter_apt_sources.signing.config.dest }}'
              --homedir '{{ _tmpres_tmpdir.path }}'
              --keyserver '{{ _iter_gpg_calls.config.keyserver }}'
              --recv-keys {{ _iter_gpg_calls.key_ids | join(' ') }}
            changed_when: false
            loop: >-
              {{ _iter_apt_sources.signing.fingerprints._export_cfgs }}
            loop_control:
              loop_var: _iter_gpg_calls


          - name: remove tmpdir again
            ansible.builtin.file:
              path: "{{ _tmpres_tmpdir.path }}"
              state: absent
            changed_when: false

        when: >-
          (_iter_apt_sources.signing.fingerprints._export_cfgs | default(False)) is truthy

    when: _iter_apt_sources.signing is truthy


  - name: add / modify / delete apt source
    ansible.builtin.apt_repository: "{{ _iter_apt_sources.config }}"

