---

  - set_fact:
      smabot_hashivault_readwrite_secrets_args: >-
        {{ _iter_save_sinks.value.downcfg }}
    no_log: true



  - ansible.builtin.include_role:
      name: smabot.hashivault.readwrite_secrets

