---

  - include_role:
      name: smabot.base.run_local
    vars:
      smabot_base_run_local_cfg:
        tasks: "{{ smabot_base_handle_syscerts_role_path }}/tasks/delegate_local/check_rootcert_exists.yml"


    ## handle root cert(s) if given path specifies a single file
  - include_tasks: handle_root_cert.yml
    loop: "{{ [ _custom_rootcert_iter ] }}"
    loop_control:
      loop_var: _rootcert_iter
    when: 
      - _result.stat.isreg


    ## handle root cert(s) if given path specifies a directory, 
    ## in that case assume all regular files inside this dir to 
    ## be custom root certs
  - include_tasks: handle_root_cert.yml
    loop: "{{ q('community.general.filetree', _custom_rootcert_iter) }}"
    loop_control:
      loop_var: _rootcert_iter
    when: 
      - _result.stat.isdir
      - _rootcert_iter.state == 'file'

