---

  - name: create sudo cfg for mapping  ==>>  {{ _iter_sudo_mappings.key }}
    ansible.builtin.template: 
      src: sudoers.j2
      dest: "{{ _iter_sudo_mappings.value.cfgfile }}"
      validate: 'visudo -cf %s'
      mode: "440"
    when: _iter_sudo_mappings.value.absent is falsy


  - name: ensure sudo cfg file does not exist
    ansible.builtin.file:
      path: "{{ _iter_sudo_mappings.value.cfgfile }}"
      state: absent
    when: _iter_sudo_mappings.value.absent is truthy

