---

  - name: >-
      check that root certificate exists  ==>>  {{ _custom_rootcert_iter }}
    ansible.builtin.stat:
      path: "{{ _custom_rootcert_iter }}"
    become: no
    delegate_to: localhost
    register: _result
    failed_when:
      - not _result.stat.exists or (not _result.stat.isreg and not _result.stat.isdir)

