---

  - name: copy java test mini prog to remote  ==>>  {{ _test_certs_urliter }}
    ansible.builtin.template:
      src: CheckSsl.java.j2
      dest: "{{ _tmp_ssltest_tmpdir.path }}/CheckSsl.java"
    changed_when: false


  - include_tasks: test_certs_java_loop.yml
    loop: "{{ handle_system_certs_args_normed.eco_systems.java._jvms }}"
    loop_control:
      loop_var: _iter_jvm

