---

  - name: convert var dir '{{ _iter_vardirs }}' to config dict
    dirtree_to_cfg:
      dirtree: "{{ q('community.general.filetree', _iter_vardirs) }}"
    register: _tmp_res
    delegate_to: localhost


    ##
    ## note: as always we must work around the collections-actions cannot update ansible varspace directly issues
    ##
  - set_fact:
      "{{ _iter_dircfg_top.key }}": "{{ _iter_dircfg_top.value }}"
    loop: "{{ _tmp_res.dircfg | dict2items() }}"
    loop_control:
      loop_var: _iter_dircfg_top


  - name: mark current dir as already expanded
    set_fact:
      smabot_base_vardirs_expanded: >-
        {{ smabot_base_vardirs_expanded | combine({_iter_vardirs: True}) }}

